language: node_js
sudo: false
node_js:
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
install:
  - npm install
before_script:
  - npm install grunt-cli istanbul
script:
  - ./node_modules/.bin/istanbul cover ./node_modules/.bin/grunt test
  - ./node_modules/.bin/grunt coveralls
